### ISSUE TITLE
Make <location> of type "geopolitical" display district before region

### ISSUE THREAD

**Issue by tacarlson** [srophe/srp-places-app#24]
Contents of a geopolitical <location> by convention are nested from largest to smallest containing place, but it would be better to display them as comma separated places from smallest to largest.  E.g. for place/883, the location would ideally be displayed "Dohuk district, ‘Amādīyā region" with the appropriate links.

**Comment by paregorios** [comment]
Doing this now on the basis of the data at it stands is potentially brittle, since it would depend on both consistent use across the dataset of particular substrings within text nodes that are not controlled vocabulary, vel sim, as well as the exact logic used to mine those terms out of the strings. I have a counter propoposal for @tacarlson : in those cases where you want a particular order for the contents of location@type=geopolitical, add the "n" attribute to each of the child nodes (region, settlement, and so forth) and populate them with integers indicating the order in which you'd like them displayed. By default, the code is currently processing such nodes in document order; I can easily add a standard check to sort them by the numeric value in the n attribute. It wouldn't be a requirement to add "n" to every child node of location, just an option when you want to control ordering explicitly. What do you think?

**Comment by tacarlson** [comment]
Actually, I was thinking just reverse the order of the children of the <location>, since convention in TEI P5 guidelines seems to be largest to smallest, while Wilmshurst is smallest to largest.  But that would require enshrining in our TEI spec a largest-to-smallest ordering which is not mandated (merely the case in every example) in the TEI guidelines.

I'm nervous about simply using @n, because the use case would be opaque to a human reading/editing our XML records, and I could easily imagine said hypothetical human botching the @n attributes.

Possible counter-counter-proposal for @paregorios and @davidamichelson : I'll change the <location> @type to be "nested" (to neutralize the unstated convention for "geopolitical") and reverse the order of the elements in the <location> so that they can be displayed in .xml order.  How does that sound?

**Comment by paregorios** [comment]
OK by me.

Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by tacarlson** [comment]
Okay, I made location type="geopolitical" into location type="nested" and reversed the order of the children to be from smallest to largest.

We discussed how we would like this location to display, and it would be great if we could do "Within Child1, within Child2, within Child3," etc., for as many children there are.

Thanks!

**Comment by davidamichelson** [comment]
Off Topic: Thomas, I also wonder in the TEI do we have a way of
differentiating Roman Province, Diocese, etc? it would be useful to browse
only by type of region.

**Comment by tacarlson** [comment]
At present we have separate types for "province", "diocese", and "region" (which means just a geographical entity, not an administrative entity like the former two).  What we don't have at present is anything linking related provinces, dioceses, and regions (e.g. a link between "Cilicia" (region) and "Cilicia II" (province)), but we can put that in at some point.
