### ISSUE TITLE
Some places not showing up in Browse by Syriac Gazetteer Number

### ISSUE THREAD

**Issue by tacarlson** [srophe/srp-places-app#66]
Last number shown is 994.  I don't know if places with ID# greater than 1000 show up in other browse views or not.

**Comment by paregorios** [comment]
This is probably simply because I've been forgetting to run the transform for the browse listing when I generate. Verifying this guess is blocked for resolving #70 (somehow along the way I've broken this tranform by modifying a template it shares with the placepage.xsl but not adding the new variable or parameter to the master template).
